version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - "8080:3000"
    environment:
      REDMINE_DB_ADAPTER: postgresql
      REDMINE_DB_ENCODING: utf8
      REDMINE_DB_HOST: db
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: example
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_POOL: 5
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: redmine
