- hosts: app_servers
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: update nginx.conf
      ansible.builtin.copy:
        src: page/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

    - name: update index.html
      ansible.builtin.copy:
        src: page/index.html
        dest: /usr/share/nginx/html/index.html
      notify:
        - restart nginx

  handlers:
      - name: restart nginx
        ansible.builtin.service:
          name: nginx
          state: reloaded
