- hosts: app_servers
  vars:
    nginx_port: 8000
    web_serv: This is server {{ server_name }}!
    current_date: "{{ lookup('pipe', \"date '+%Y-%m-%d %H:%M:%S'\" ) }}"
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - redis-server
        - postgresql
        - nginx

    - name: add test users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: testuser1, groups: vagrant }
        - { name: testuser2, groups: root }

    - name: update nginx.conf
      ansible.builtin.template:
        src: page/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

    - name: update index.html
      ansible.builtin.template:
        src: page/index.html
        dest: /usr/share/nginx/html/index.html
      notify:
        - restart nginx

  handlers:
      - name: restart nginx
        ansible.builtin.service:
          name: nginx
          state: reloaded